# MCP Security Scanner Configuration
# Environment variables can be used with ${VAR_NAME:default_value} syntax

# Scanner Configuration
scanner:
  # Directory containing security policies
  policy_directory: ./policies
  
  # Default policy to use when none specified
  default_policy: critical-security
  
  # Maximum number of concurrent scanning jobs
  max_concurrent_jobs: 5
  
  # Timeout for scanner operations (e.g., 30s, 1m, 2h)
  timeout: 30s
  
  # Maximum number of retries for failed operations
  max_retries: 3
  
  # User agent string for HTTP requests
  user_agent: MCP-Security-Scanner/1.0.0
  
  # Logging level for scanner operations
  log_level: INFO
  
  # Output configuration
  output:
    # Default output format (json, html, pdf, text)
    default_format: json
    
    # Directory for saving reports
    directory: ./reports
    
    # Base filename for generated reports
    filename_base: mcp_security_report

# Proxy Configuration
proxy:
  # Host address for the proxy server
  host: localhost
  
  # Port for the proxy server
  port: 8080
  
  # Timeout for proxy operations
  timeout: 30s
  
  # Maximum buffer size in MB for proxy operations
  max_buffer_mb: 10
  
  # Enable TLS/SSL for the proxy
  enable_tls: false
  
  # Certificate file for TLS (required if enable_tls is true)
  cert_file: ""
  
  # Private key file for TLS (required if enable_tls is true)
  key_file: ""
  
  # Webhook URL for real-time alerts
  alert_webhook: ""

# Integration Configuration
integration:
  # SIEM Integration
  siem:
    # Enable SIEM integration
    enabled: false
    
    # SIEM API endpoint
    endpoint: ${SIEM_ENDPOINT:}
    
    # SIEM API key for authentication
    api_key: ${SIEM_API_KEY:}
    
    # Index/destination for SIEM events
    index: mcp-security
  
  # SOAR Integration
  soar:
    # Enable SOAR integration
    enabled: false
    
    # SOAR API endpoint
    endpoint: ${SOAR_ENDPOINT:}
    
    # SOAR API key for authentication
    api_key: ${SOAR_API_KEY:}
    
    # Username for SOAR authentication
    username: ${SOAR_USERNAME:}
  
  # Slack Notifications
  slack:
    # Enable Slack notifications
    enabled: false
    
    # Slack webhook URL
    webhook_url: ${SLACK_WEBHOOK_URL:}
    
    # Slack channel for notifications
    channel: "#security-alerts"
    
    # Bot username for Slack messages
    username: "MCP Security Scanner"
    
    # Icon emoji for Slack messages
    icon_emoji: ":shield:"
    
    # Minimum severity level for Slack notifications
    min_severity: HIGH

# Logging Configuration
logging:
  # Log level (DEBUG, INFO, WARN, ERROR)
  level: INFO
  
  # Log format (json, text)
  format: json
  
  # Log output destination (stdout, stderr, file path)
  output: stdout
  
  # Maximum log file size in MB (for file output)
  max_size_mb: 100
  
  # Maximum number of old log files to retain
  max_backups: 3
  
  # Maximum number of days to retain log files
  max_age: 30
